version: "3"
services:
  devcontainer:
    build:
      context: .
      args:
        VARIANT: "16"
    volumes:
    - ..:/workspace:cached
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    command: /bin/sh -c "while sleep 1000; do :; done"
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '1.0'
          memory: 2G
